{% set name = "git-pull-request" %}
{% set version = "6.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0c8fd5122a6783e9a92660cd43b94a933d6aadebfd1bb07d276fc60c1013973

build:
  number: 0
  noarch: python
  entry_points:
    - git-pull-request = git_pull_request:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - git
    - python >=3.7
    - attrs
    - daiquiri
    - pygithub
    - requests

test:
  imports:
    - git_pull_request
    - git_pull_request.tests
  commands:
    - pip check
    - git-pull-request --help
  requires:
    - pip

about:
  home: https://github.com/Mergifyio/git-pull-request
  summary: Command line tool to send GitHub pull requests
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nerohmot
